---
name: Functional Tests (Remote)

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Setup Mojo
        id: setup-mojo
        uses: fabasoad/setup-mojo-action@main
        continue-on-error: true
      - name: Validate failure
        if: ${{ matrix.os == 'windows' }}
        run: |
          if [ "${{ steps.setup-mojo.outcome }}" != "failure" ]; then
            echo "::error title=Test failed::Setting up Mojo was expected to fail"
            exit 1
          fi
      - name: Validate script
        if: ${{ matrix.os != 'windows' }}
        run: |
          echo 'fn main():' > hello-world.mojo
          echo '    print("Hello, world!")' >> hello-world.mojo
          [ "$(mojo hello-world.mojo)" = "Hello, world!" ] || exit 1;
